### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by 15951836388** [exatb/GJKEPA#1]
Can you give some examples? 

and support for spheres, cylinders, ellipses, and more

**Comment by exatb** [comment]
Hi! This code is part of my project there no need to check spheres, cylinders etc. But you can easily add ones. I will prepare some simple examples and add them to this repository.

**Comment by exatb** [comment]
I created a very simple example of multi-body interaction and put it on
https://github.com/exatb/Rockfall
You can download and test it.

**Comment by 15951836388** [comment]
Thank you very much
